loader: "lettuce"
tables:
  nation:
    id: 1
    file: "data/nation.tbl"
    partitionCols:
      - "1"
  region:
    id: 2
    file: "data/region.tbl"
    partitionCols:
      - "1"
  part:
    id: 3
    file: "data/part.tbl"
    partitionCols:
      - "4"
  supplier:
    id: 4
    file: "data/supplier.tbl"
    partitionCols:
      - "4"
  partsupp:
    id: 5
    file: "data/partsupp.tbl"
    partitionCols:
      - "2"
  customer:
    id: 6
    file: "data/customer.tbl"
    partitionCols:
      - "4"
  orders:
    id: 7
    file: "data/orders.tbl"
    partitionCols:
      - "5"
  lineitem:
    id: 8
    file: "data/lineitem.tbl"
    partitionCols:
      - "3"
